// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFoP6ewHLxKAcD7dReIdhnrZrpZi2At84',
    appId: '1:501879961310:web:1ed7e2cda436ca1622b44f',
    messagingSenderId: '501879961310',
    projectId: 'project2-42954',
    authDomain: 'project2-42954.firebaseapp.com',
    storageBucket: 'project2-42954.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsDVcAtTo_Jy0Gmicfv38ojYYkixfnZQ4',
    appId: '1:501879961310:android:bdcd0a869295dd3c22b44f',
    messagingSenderId: '501879961310',
    projectId: 'project2-42954',
    storageBucket: 'project2-42954.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrxQ15eWUine6fihOSVOh2Jj0lKLAtH74',
    appId: '1:501879961310:ios:e196accba87ecb0622b44f',
    messagingSenderId: '501879961310',
    projectId: 'project2-42954',
    storageBucket: 'project2-42954.appspot.com',
    iosBundleId: 'com.example.project2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrxQ15eWUine6fihOSVOh2Jj0lKLAtH74',
    appId: '1:501879961310:ios:0bc5686d0d50c85222b44f',
    messagingSenderId: '501879961310',
    projectId: 'project2-42954',
    storageBucket: 'project2-42954.appspot.com',
    iosBundleId: 'com.example.project2.RunnerTests',
  );
}
